### ISSUE TITLE
Can someone update the react version and the respective module version  ?

### ISSUE THREAD

**Issue by sridarm** [pvoznyuk/react-pretty-numbers#4]
When I use this module in the production version, react Chrome plugin display that it uses old version of React, can someone please update the react version of this module and its dependencies as well.

**Comment by pvoznyuk** [comment]
@sridarm yes, i'll do that in a couple of days

**Comment by sridarm** [comment]
Thanks @pvoznyuk

**Comment by pvoznyuk** [comment]
updated in a new version
